Glenda_ERP_Project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('',include('Glenda_App.urls')),
    path('', include('register_app.urls')),
    path('', include('purchase_app.urls')),
    path('', include('production_app.urls')),
    path('', include('inventory_app.urls')),
    path('', include('logistics_app.urls')),
    path('', include('vendor_app.urls')),
    path('',include('hr_app.urls')),
    path('', include('customer_app.urls')),
    path('',include('rd_app.urls')),
    path('',include('accounting_app.urls'))

]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hr_app/urls.py
from django.urls import path
from hr_app import views
urlpatterns = [
    path('employee_list_and_verify',views.employee_list_and_verify,name='employee_list_and_verify'),
    path('employee_details_modal',views.employee_details_modal,name='employee_details_modal'),
    path('employee_detail',views.employee_detail,name='employee_detail'),
    path('verify_employee',views.verify_employee,name='verify_employee'),
    path('AddDetails',views.AddDetails,name='AddDetails'),
    path('view_employee_profile/<int:id>',views.view_employee_profile,name='view_employee_profile'),
    path('update_employee_details/<int:id>',views.update_employee_details,name='update_employee_details'),
    path('resign_employee_details/<int:id>',views.resign_employee_details,name='resign_employee_details'),
    path('employee_search_and_export',views.employee_search_and_export,name='employee_search_and_export'),
    path('view_leave_list',views.view_leave_list,name='view_leave_list'),
    path('approve_leave_request/', views.approve_leave_request, name='approve_leave_request'),
    path('reject_leave_request/', views.reject_leave_request, name='reject_leave_request'),
    path('my_leave_request', views.my_leave_request, name='my_leave_request'),
    path('request_leave', views.leave_request_form, name='leave_request_form'),
    path('search_approved_leave_requests',views.search_approved_leave_requests,name='search_approved_leave_requests'),
    path('employee/', views.employee_detail, name='employee_detail'),
    path('leave_history/<int:id>',views.leave_history,name='leave_history'),
    path('create_payroll/<int:id>',views.create_payroll,name='create_payroll'),
    path('payroll_summary/<int:id>',views.payroll_summary,name='payroll_summary'),
    path('payroll-by-month/', views.payroll_by_month, name='payroll_by_month'),
    path('add_employee_details/<int:id>', views.add_employee_details, name='add_employee_details'),
    path('Employee_request_list',views.employee_request_list,name='Employee_request_list'),
    path('view_my_profile',views.view_my_profile,name='view_my_profile'),
    path('verify_leave_list',views.verify_leave_list,name='verify_leave_list'),
    path('verify_leave_request',views.verify_leave_request,name='verify_leave_request'),
    path('reject_verify_leave_request',views.reject_verify_leave_request,name='reject_verify_leave_request'),
    path('attendance_detail',views.attendance_view,name='attendance_detail'),
    path('senior_approval/<int:id>/', views.senior_resignation_approval, name='senior_resignation_approval'),
    path('hr_approval/<int:id>/', views.hr_resignation_approval, name='hr_resignation_approval'),
    path('Resign_list_for_senior',views.Resign_list_for_senior,name='Resign_list_for_senior'),
    path('Resign_list_for_hr',views.Resign_list_for_hr,name='Resign_list_for_hr'),
    path('attendance/reports/', views.attendance_reports, name='attendance_reports'),
    path('attendance/', views.mark_attendance, name='mark_attendance'),
    path('fetch_attendance',views.fetch_attendance,name='fetch_attendance'),
    path('verify_employee_by_senior',views.verify_employee_by_senior,name='verify_employee_by_senior'),
    path('holiday-calendar/', views.holiday_calendar, name='holiday_calendar'),
    path('fetch-holidays/', views.fetch_holidays, name='fetch_holidays'),
    path('add-holiday/', views.add_holiday, name='add_holiday'),
    path('upload-attendance/', views.upload_attendance_file, name='upload_attendance'),
]

hr_app/models.py
from datetime import datetime, date
from django.utils import timezone
from django.db import models
from register_app.models import CustomUser
from django.core.exceptions import ValidationError
from decimal import Decimal
import re

class EmployeeDetails(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, related_name='employeedetails')
    status = models.CharField(max_length=50, choices=[('verified', 'Verified'), ('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending')
    joining_date = models.DateField(null=True, blank=True)
    basic = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    street = models.CharField(max_length=150, null=True, blank=True)
    pincode = models.CharField(max_length=9, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    landmark = models.CharField(max_length=100, null=True, blank=True)
    building = models.CharField(max_length=100, null=True, blank=True)
    district = models.CharField(max_length=120, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)

    BloodGroupTypes = (
        ('AB+', 'AB+'),
        ('B+', 'B+'),
        ('A+', 'A+'),
        ('O+', 'O+'),
        ('AB-', 'AB-'),
        ('B-', 'B-'),
        ('A-', 'A-'),
        ('O-', 'O-'),
    )

    employee_blood_groups = models.CharField(max_length=100, choices=BloodGroupTypes, default='AB+', blank=True)
    pf_no = models.CharField(max_length=22, unique=True, null=True, blank=True)  # Allow NULL and blank
    employee_esi_no = models.CharField(max_length=17, unique=True, null=True, blank=True)  # Allow NULL and blank
    qualification = models.CharField(max_length=100, blank=True)
    qualification_file = models.FileField(upload_to='qualification_files/', null=True, blank=True)
    experience = models.CharField(max_length=100, blank=True)
    experience_file = models.FileField(upload_to='experience_files/', null=True, blank=True)
    id_proof_types = (
        ('AADHAR', 'AADHAR'),
        ('PASSPORT', 'PASSPORT'),
        ('PAN CARD', 'PAN CARD'),
        ('OTHERS', 'OTHERS')
    )
    other_id_proof_types = (
        ('DRIVING LICENSE', 'DRIVING LICENSE'),
        ('F AND B LICENSE', 'F AND B LICENSE')
    )
    GENDER_TYPES = (
        ('MALE','MALE'),
        ('FEMALE','FEMALE'),
        ('OTHERS','OTHERS'),
        ('PREFER NOT TO SAY','PREFER NOT TO SAY')
    )
    id_proof_type = models.CharField(max_length=20, choices=id_proof_types)
    other_id_proof_type = models.CharField(max_length=20, choices=other_id_proof_types, blank=True, null=True)
    id_proof_type_number = models.CharField(max_length=20, null=True, blank=True, unique=True)
    id_proof_file = models.FileField(upload_to='ID_PROOF/', null=True, blank=True)
    validity = models.DateTimeField(null=True, blank=True)
    nsr = models.FileField(upload_to='PCC/', null=True, blank=True)
    pcc = models.FileField(upload_to='NSR/', null=True, blank=True)
    resume = models.FileField(upload_to='RESUME/',null=True,blank=True)
    gender = models.CharField(max_length=20,choices=GENDER_TYPES,null=True,blank=True)
    bank_details = models.FileField(upload_to='BANK/',null=True,blank=True)

    verified = models.BooleanField(default=False)

    def clean(self):
        # Convert empty strings to None for unique fields
        if self.pf_no == '':
            self.pf_no = None
        if self.employee_esi_no == '':
            self.employee_esi_no = None

        # Custom validation to ensure at least one field is filled
        if not self.id_proof_type and not self.id_proof_file:
            raise ValidationError('You must provide either an Aadhar number or upload a file.')

        if self.other_id_proof_type == "DRIVING LICENSE":
            # Example: Driving License must match a specific format
            if not re.match(r"^[A-Z]{2}\d{13}$", self.id_proof_type_number):
                raise ValidationError({
                    'id_proof_type_number': 'Driving License must follow the format: 2 uppercase letters followed by 13 digits (e.g., DL0123456789123).'
                })

        if self.other_id_proof_type == "F AND B LICENSE":
            # Example: F and B License must match a different format
            if not re.match(r"^FB-\d{10}$", self.id_proof_type_number):
                raise ValidationError({
                    'id_proof_type_number': 'F and B License must follow the format: FB- followed by 10 digits (e.g., FB-1234567890).'
                })

        if self.id_proof_type == "AADHAR":
            if not re.match(r"^\d{12}$", self.id_proof_type_number):
                raise ValidationError({
                    'id_proof_type_number': 'AADHAR CARD must follow the format: 2 uppercase letters followed by 13 digits (e.g., 596206677449).'
                })

        if self.id_proof_type == "PAN CARD":
            if not re.match(r"^[A-Z]{5}\d{4}[A-Z]{1}$", self.id_proof_type_number):
                raise ValidationError({
                    'id_proof_type_number': 'PAN CARD must follow the format: FB- followed by 10 digits (e.g., ADYPM6101D).'
                })

        if self.id_proof_type == "PASSPORT":
            if not re.match(r"^[A-Z]{1}\d{7}$", self.id_proof_type_number):
                raise ValidationError({
                    'id_proof_type_number': 'PASSPORT must follow the format: FB- followed by 10 digits (e.g., J8369854).'
                })

        if self.id_proof_type_number:
            existing_id_proof = EmployeeDetails.objects.filter(
                id_proof_type_number=self.id_proof_type_number
            ).exclude(pk=self.pk)
            if existing_id_proof.exists():
                raise ValidationError({'id_proof_type_number': 'This ID proof number already exists.'})

            # Validate ESI number for duplicates
        if self.employee_esi_no:
            existing_esi = EmployeeDetails.objects.filter(employee_esi_no=self.employee_esi_no).exclude(pk=self.pk)
            if existing_esi.exists():
                raise ValidationError({'employee_esi_no': 'This ESI number already exists.'})

        if self.pf_no:
            existing_pf = EmployeeDetails.objects.filter(pf_no=self.pf_no).exclude(pk=self.pk)
            if existing_pf.exists():
                raise ValidationError({'pf_no': 'This PF number already exists.'})

        if self.validity and self.validity < timezone.now():
            raise ValidationError({'validity': 'The validity date cannot be in the past.'})

    def check_complete(self):
        # List of required fields to consider the details as complete
        required_fields = [self.basic, self.pf_no, self.employee_esi_no]
        if all(required_fields):
            self.is_complete = True
        else:
            self.is_complete = False

    def save(self, *args, **kwargs):
        # Update completeness status before saving
        self.check_complete()
        super(EmployeeDetails, self).save(*args, **kwargs)



class RequestLeave(models.Model):
    employee = models.ForeignKey(EmployeeDetails, on_delete=models.CASCADE, null=True,related_name='leaverequest')

    LEAVE_TYPE_CHOICES = (
        ('Sick Leave', 'Sick Leave'),
        ('Casual Leave', 'Casual Leave'),
        ('Paid Leave', 'Paid Leave'),
    )

    leave_type = models.CharField(max_length=100, choices=LEAVE_TYPE_CHOICES)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    reason = models.CharField(max_length=120, null=True)

    Approval_Type = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Rejected', 'Rejected'),
    )

    verification_status = models.CharField(max_length=100, choices=Approval_Type, default='Pending')
    approval_status = models.CharField(max_length=100, choices=Approval_Type, default='Pending')
    rejection_reason = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.employee} - {self.approval_status}"


class Payroll(models.Model):
    employee = models.ForeignKey(EmployeeDetails, on_delete=models.CASCADE)

    # Earnings
    hra = models.DecimalField(max_digits=10, decimal_places=2)
    da = models.DecimalField(max_digits=10, decimal_places=2)
    ot = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=Decimal('0.00'))
    leave_plus = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=Decimal('0.00'))

    medical = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=Decimal('0.00'))
    insurance = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=Decimal('0.00'))
    ta = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=Decimal('0.00'))
    food_allowance = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True,
                                         default=Decimal('0.00'))

    # Deductions
    canteen_expense = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True,
                                          default=Decimal('0.00'))
    pf = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=Decimal('0.00'))
    esi = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=Decimal('0.00'))

    # Bonuses
    bonuses = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=Decimal('0.00'))

    # Computed field
    net_pay = models.DecimalField(max_digits=10, decimal_places=2)
    pay_date = models.DateField()

    def __str__(self):
        return f"{self.employee}"

class Resignation(models.Model):
    ACTIVE = 'Active'
    RESIGNED = 'Resigned'
    PENDING = 'Pending'
    APPROVED_BY_SENIOR = 'Approved by Senior'

templates/customer/registration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="page-content-wrapper">
    <div class="container-fluid">
        <!-- Page Title and Breadcrumb -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="btn-group float-right">
                        <ol class="breadcrumb hide-phone p-0 m-0">
                            <li class="breadcrumb-item"><a href="#"></a></li>
                            <li class="breadcrumb-item"><a href="#"></a></li>
                            <li class="breadcrumb-item active"></li>
                        </ol>
                    </div>
                    <h4 class="page-title">Customer Details</h4>
                </div>
            </div>
        </div>

        <!-- Form Section -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="mt-0 header-title">Vendor Details</h4>
                        <p class="text-muted mb-4 font-13">Please fill in the vendor details below.</p>
                        <form action="" method="post">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            <div class="row">
                                <div class="col-xl-6">
                                    <!-- Company Name -->
                                    <div class="form-group row">
                                        <label for="id_name" class="col-sm-4 col-form-label">Name</label>
                                        <div class="col-sm-8">
                                            {{ form.name }}
                                            {% for error in form.name.errors %}
                                                <span class="text-danger">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>

                                    <!-- Address -->
                                    <div class="form-group row">
                                        <label for="id_address" class="col-sm-4 col-form-label">Address</label>
                                        <div class="col-sm-8">
                                            {{ form.address }}
                                            {% for error in form.address.errors %}
                                                <span class="text-danger">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>

                                    <!-- Pincode -->
                                    <div class="form-group row">
                                        <label for="id_pincode" class="col-sm-4 col-form-label">Pin Code</label>
                                        <div class="col-sm-8">
                                            {{ form.pincode }}
                                            {% for error in form.pincode.errors %}
                                                <span class="text-danger">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>

                                    <!-- District -->
                                    <div class="form-group row">
                                        <label for="id_district" class="col-sm-4 col-form-label">District</label>
                                        <div class="col-sm-8">
                                            {{ form.district }}
                                            {% for error in form.district.errors %}
                                                <span class="text-danger">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>

                                    <!-- State -->
                                    <div class="form-group row">
                                        <label for="id_state" class="col-sm-4 col-form-label">State</label>
                                        <div class="col-sm-8">
                                            {{ form.state }}
                                            {% for error in form.state.errors %}
                                                <span class="text-danger">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>

                                    <!-- Email -->
                                    <div class="form-group row">
                                        <label for="id_email" class="col-sm-4 col-form-label">Email</label>
                                        <div class="col-sm-8">
                                            {{ form.email }}
                                            {% for error in form.email.errors %}
                                                <span class="text-danger">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>

                                    <!-- Phone Number -->
                                    <div class="form-group row">
                                        <label for="id_phone_number" class="col-sm-4 col-form-label">Phone Number</label>
                                        <div class="col-sm-8">
                                            {{ form.phone_number }}
                                            {% for error in form.phone_number.errors %}
                                                <span class="text-danger">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>

                                <div class="col-xl-6">
                                    <!-- GST -->
                                    <div class="form-group row">
                                        <label for="id_GST_yes_or_no" class="col-sm-4 col-form-label">Do you have GST?</label>
                                        <div class="col-sm-8">
                                            {{ form.GST_yes_or_no }}
                                            {% for error in form.GST_yes_or_no.errors %}
                                                <span class="text-danger">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>

                                    <!-- GST Number -->
                                    <div class="form-group row">
                                        <label for="id_GST_number" class="col-sm-4 col-form-label">GST Number</label>
                                        <div class="col-sm-8">
                                            {{ form.GST_number }}
                                            {% for error in form.GST_number.errors %}
                                                <span class="text-danger">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>

                                    <!-- PAN -->
                                    <div class="form-group row">
                                        <label for="id_pan_yes_or_no" class="col-sm-4 col-form-label">Do you have a PAN?</label>
                                        <div class="col-sm-8">
                                            {{ form.pan_yes_or_no }}
                                            {% for error in form.pan_yes_or_no.errors %}
                                                <span class="text-danger">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>

                                    <!-- PAN Number -->
                                    <div class="form-group row">
                                        <label for="id_PAN_number" class="col-sm-4 col-form-label">PAN Number</label>
                                        <div class="col-sm-8">
                                            {{ form.PAN_number }}
                                            {% for error in form.PAN_number.errors %}
                                                <span class="text-danger">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Submit Button -->
                            <div class="form-group mb-0">
                                <div>
                                    <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                                    <button type="reset" class="btn btn-secondary waves-effect m-l-5">Cancel</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div> <!-- end col -->
        </div> <!-- end row -->

        <!-- jQuery code to fetch location based on pincode -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script>
            $(document).ready(function() {
                // Input field for pincode
                $('#id_pincode').on('input', function() {
                    var pincode = $(this).val();

                    // Ensure the pincode is 6 digits long
                    if (pincode.length === 6) {
                        // Use India's Post Office API to fetch location details
                        $.ajax({
                            url: 'https://api.postalpincode.in/pincode/' + pincode,
                            method: 'GET',
                            success: function(response) {
                                if (response[0].Status === 'Success') {
                                    var postOffice = response[0].PostOffice[0];
                                    var district = postOffice.District;
                                    var state = postOffice.State;

                                    // Fill the form fields with the fetched data
                                    $('#id_district').val(district);
                                    $('#id_state').val(state);
                                } else {
                                    alert('Invalid Pincode');
                                }
                            },
                            error: function() {
                                alert('Error fetching details. Please try again later.');
                            }
                        });
                    }
                });
            });
        </script>

        <script>
            document.addEventListener('DOMContentLoaded', function () {
                const panYesNoField = document.getElementById('id_pan_yes_or_no');
                const vendorPANField = document.getElementById('id_PAN_number');

                // Function to toggle the disabled state of the PAN Number field
                function togglePANField() {
                    if (panYesNoField.value === 'yes') {
                        vendorPANField.disabled = false;
                    } else {
                        vendorPANField.disabled = true;
                        vendorPANField.value = '';
                    }
                }

                // Initial check on page load
                togglePANField();

                // Add event listener for changes to the PAN Yes/No field
                panYesNoField.addEventListener('change', togglePANField);
            });
        </script>
    </div>
</div>
{% endblock %}

templates/customer/search_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="page-content-wrapper">

    <div class="container-fluid">
        {% for i in view %}
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="btn-group float-right">
                        <div class="btn-group mo-mb-2">
                            <button type="button" class="btn btn-success btn-lg" fdprocessedid="gg5obj">Export as</button>
                            <button type="button" class="btn btn-lg btn-success dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" fdprocessedid="jdvfec">
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(79px, 38px, 0px); top: 0px; left: 0px; will-change: transform;">
                                {% comment %} <a class="dropdown-item" href="{% url '' i.id %}">PDF </a> {% endcomment %}
                            </div>
                        </div>
                    </div>
                    <h4 class="page-title">Customer Details</h4>
                </div>
            </div>
        </div>
        <!-- end page title end breadcrumb -->
        <div class="row">
            <div class="col-12">
                <div class="card mt-4" style="margin-top: 20px;">
                    <div class="card-body" >

                        <h4 class="mt-0 header-title"></h4>
                        <p class="text-muted mb-4 font-13"></p>


                        <table class="table mb-2 " id="my-table">
                            <tbody>
                                <tr>
                                    <th>Name</th>
                                    <td>{{ i.name }}</td>
                                </tr>
                                <tr>
                                    <th>Email</th>
                                    <td>{{ i.address }}</td>
                                </tr>
                            
                                <tr>
                                    <th>Pincode</th>
                                    <td>{{ i.pincode }}</td>
                                </tr>
                              
                                <tr>
                                    <th>State</th>
                                    <td>{{ i.state }}</td>
                                </tr>
                                <tr>
                                    <th>District</th>
                                    <td>{{ i.district }}</td>
                                </tr>
                                <tr>
                                    <th>Email</th>
                                    <td>{{ i.email }}</td>
                                </tr>
                                <tr>
                                    <th>GST</th>
                                    <td>{{ i.GST_yes_or_no }}</td>
                                </tr>
                                <tr>
                                    <th>GST Number</th>
                                    <td>{{ i.GST_number }}</td>
                                </tr>
                                <tr>
                                    <th>PAN </th>
                                    <td>{{ i.pan_yes_or_no }}</td>
                                </tr>
                                <tr>
                                    <th>PAN Number </th>
                                    <td>{{ i.PAN_number }}</td>
                                </tr>

                                <tr>
                                    <th>Phone Number</th>
                                    <td>{{ i.phone_number }}</td>
                                </tr>

                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div> <!-- end col -->
        </div> <!-- end row -->

    </div><!-- container -->

</div> <!-- Page content Wrapper -->

{% endblock %}